# codecov:
#   require_ci_to_pass: yes

# coverage:
#   precision: 2
#   round: nearest
#   range: "90...100"
#   status:
#     project:
#       default:
#         base: auto
#         target: auto
#         threshold: 0.1%
#         if_not_found: success
#     backend:
#       paths:
#         - backend
#     frontend:
#       paths:
#         - src

# comment:
#   layout: "reach,diff,flags,tree"
#   behavior: default


coverage:
  status:
    project:
      default:
        target: 90%
      backend:
        target: 80%
        flags:
          - backend
flags:
  backend:
  paths:
    - backend/
