version: 2.1
orbs:
  # Cypress Orb simplifies installing, caching, and running Cypress
  cypress: cypress-io/cypress@1
  # https://circleci.com/blog/making-code-coverage-easy-to-see-with-the-codecov-orb/
  # https://circleci.com/developer/orbs/orb/codecov/codecov
  codecov: codecov/codecov@1

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
commands:
  report-coverage:
    description: |
      Store coverage report as an artifact and send it to Codecov service.
    parameters:
      flag:
        type: string
        default: ""
    steps:
      - store_artifacts:
          path: coverage
      - run: npx nyc report --reporter=text || true
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: << parameters.flag >>

workflows:
  linux:
    jobs:
      - cypress/install:
          executor: cypress/base-12-18-3
          yarn: true

      - cypress/run:
          name: API tests
          executor: cypress/base-12-18-3
          spec: "cypress/tests/api/*"
          yarn: true
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          requires:
            - cypress/install
          group: api
          post-steps:
            - report-coverage:
                flag: backend
          # do not preserve the workspace in this job, since
          # there are no jobs that follow it
          no-workspace: true

      - cypress/run:
          name: E2E desktop tests
          executor: cypress/base-12-18-3
          yarn: true
          spec: "cypress/tests/ui/*"
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          requires:
            - cypress/install
          parallel: true
          parallelism: 2
          group: e2e
          post-steps:
            - report-coverage
          # do not preserve the workspace in this job, since
          # there are no jobs that follow it
          no-workspace: true

      - cypress/run:
          name: E2E mobile tests
          executor: cypress/base-12-18-3
          yarn: true
          spec: "cypress/tests/ui/*"
          config: "viewportWidth=375,viewportHeight=667"
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          requires:
            - cypress/install
          parallel: true
          parallelism: 2
          group: "e2e mobile"
          post-steps:
            - report-coverage
          # do not preserve the workspace in this job, since
          # there are no jobs that follow it
          no-workspace: true
